### ISSUE TITLE
Aplikacja nie działa po zmianach na stronie Tauron Elicznik

### ISSUE THREAD

**Issue by maverick8189** [lukaszczerpak/elicznik#1]
Hej,
Po zmianach na stronie Elicznik aplikacja nie pobiera danych z csv.
Czy jest szansa na dostosowanie kodu pod obecną stronę?
Zmiany które zauważyłem:
![image](https://user-images.githubusercontent.com/94139840/211558584-e4b83072-37ae-40fe-b875-aa6da6b66edc.png)
![image](https://user-images.githubusercontent.com/94139840/211558691-75c2cc88-4bbb-45e7-a3d7-39ba142b7021.png)

**Comment by lukaszczerpak** [comment]
Jestem w trakcie dostosowywania aplikacji do nowego API. Na dniach będzie nowa wersja.

**Comment by lukaszczerpak** [comment]
Zrobione: https://github.com/lukaszczerpak/elicznik/commit/68bc887f8bb0738fd1df3ebd0215b466ee97ea40

**Comment by maverick8189** [comment]
Super, sprawdziłem i działa jak wcześniej. Wydaje mi się tylko, że jest problem przy opcji elicznik process, tj. przy miesięcznym bilansowaniu. Nic nie pojawia się w bazie. Wydaje mi się, że w query.go powinna być zmienna przy "measurement ==" pobierana z configu a masz wprowadzoną stałą nazwę "licznik". Możesz mi jeszcze przybliżyć jak działa "Storage":         string(storageSerialized)? Bo przy query w influxdb wyrzuca mi błąd przy tym.

**Comment by lukaszczerpak** [comment]
Dzięki! Poprawiłem :)

Jeśli chodzi o query, to jedynie mogę przypuszczać ze uzywasz domyślnie agregacji "mean" podczas gdy trzeba uzyc "last". Wartosc Storage jest tablica i stad agregacja nie dziala. Możesz tez wrzucic ponizsze query ktore na pewno dziala (wybierz okres np. 2023-01-01 00:00:00 - now):

```
from(bucket: "tauron")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "licznik_balance")
```

Storage jest tablica zawierającą maksymalnie 12 elementów reprezentujących zachowaną energię do wykorzystania. Z racji, że prosumenci mają 12 miesięcy na wykorzystanie zachowanej energii, a podczas bilansowania najpierw jest używana energie zachowana z bilansowanego miesiąca, a dopiero później z magazynu, niezbędne jest trzymanie tego w takiej postaci, a nie jako jedna liczba.
